* Some notes on progression

The progression here makes use of a spiral curriculum like one where you get exposed to a distinct perspective to computer science and then keep looking at from different angles till you get one full revolution.
Once a full coverage is received, we repeat from the first part again but this time with slightly tough topics to learn.

⚪ Overview
- Map of Computer Science
- What is Computer Science?
- Why learn particular topics?

🔴 Hands on
- Building Software
- Problem Solving skills
- Shipping Software

🟠 User Interface Design
- UI Designing
- Engineering
- Delivery Process

🟡 Higher Level Architecture:
- Algorithms
- Database

🟢 Lower Level Architecture
- Computer Organization
- OS
- Networking
- Assembly

🟣 Abstractions
- Programming Languages
- Paradigms
- Computability
- Theory

🔵 Distributed Systems
- Networks
- Algorithms

🟤 Applications
- Graphics
- Cryptography
- Data Science

⚫ Frontiers
- Artificial Intelligence
- Machine Learning
- Quantum Computing

